[package]
authors = ["akash"]
edition = "2018"
name = "deckterra"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.37"
chrono = {version = "0.4.19", features = ["serde"]}
diesel = {version = "1.4", features = ["sqlite", "numeric", "chrono"]}
dotenv = "0.15"
futures-util = "*"
hyper = {version = "0.14", features = ["client", "http2"]}
hyper-rustls = "0.22"
lazy_static = "1.4.0"
log = "0.4.11"
lordeckcodes = "0.4.0"
pretty_env_logger = "0.4.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0.61"
serde_qs = "0.8.2"
tokio = {version = "1.0.1", features = ["macros", "rt-multi-thread", "time"]}
tokio-stream = "0.1.0"
