[package]
authors = ["akash"]
edition = "2018"
name = "deckterra"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.8"
log = "0.4.11"
pretty_env_logger = "0.4.0"
reqwest = {version = "0.10", features = ["json"]}
serde = {version = "1.0", features = ["derive"]}
tokio = {version = "0.2.5", features = ["full"]}
